User shall be able to convert Match to string
Overridden Match::toString() so it will return a string describing it in following order: home team name, home team score, separator'-', away team name, away team score. Each element will be additionally separated by space.

Exception: if any of names is empty, then space separator after it will be omitted.